# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Channel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, timestamp: str=None):  # noqa: E501
        """Channel - a model defined in Swagger

        :param name: The name of this Channel.  # noqa: E501
        :type name: str
        :param timestamp: The timestamp of this Channel.  # noqa: E501
        :type timestamp: str
        """
        self.swagger_types = {
            'name': str,
            'timestamp': str
        }

        self.attribute_map = {
            'name': 'name',
            'timestamp': 'timestamp'
        }
        self._name = name
        self._timestamp = timestamp or datetime.utcnow().strftime(("%Y-%m-%d %H:%M:%SZ"))

    @classmethod
    def from_dict(cls, dikt) -> 'Channel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The channel of this Channel.  # noqa: E501
        :rtype: Channel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Channel.

        Name of channel  # noqa: E501

        :return: The name of this Channel.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Channel.

        Name of channel  # noqa: E501

        :param name: The name of this Channel.
        :type name: str
        """

        self._name = name

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this Channel.

        Last update  # noqa: E501

        :return: The timestamp of this Channel.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this Channel.

        Last update  # noqa: E501

        :param timestamp: The timestamp of this Channel.
        :type timestamp: str
        """

        self._timestamp = timestamp
