# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Host(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, channels: List[str]=None, state: str='UP', timestamp: str=None):  # noqa: E501
        """Host - a model defined in Swagger

        :param name: The name of this Host.  # noqa: E501
        :type name: str
        :param channels: The channels of this Host.  # noqa: E501
        :type channels: List[str]
        :param state: The state of this Host.  # noqa: E501
        :type state: str
        :param timestamp: The timestamp of this Host.  # noqa: E501
        :type timestamp: str
        """
        self.swagger_types = {
            'name': str,
            'channels': List[str],
            'state': str,
            'timestamp': str
        }

        self.attribute_map = {
            'name': 'name',
            'channels': 'channels',
            'state': 'state',
            'timestamp': 'timestamp'
        }
        self._name = name
        self._channels = channels
        self._state = state
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'Host':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The host of this Host.  # noqa: E501
        :rtype: Host
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Host.

        Name of host to create  # noqa: E501

        :return: The name of this Host.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Host.

        Name of host to create  # noqa: E501

        :param name: The name of this Host.
        :type name: str
        """

        self._name = name

    @property
    def channels(self) -> List[str]:
        """Gets the channels of this Host.

        Channels of host to message  # noqa: E501

        :return: The channels of this Host.
        :rtype: List[str]
        """
        return self._channels

    @channels.setter
    def channels(self, channels: List[str]):
        """Sets the channels of this Host.

        Channels of host to message  # noqa: E501

        :param channels: The channels of this Host.
        :type channels: List[str]
        """

        self._channels = channels

    @property
    def state(self) -> str:
        """Gets the state of this Host.


        :return: The state of this Host.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Host.


        :param state: The state of this Host.
        :type state: str
        """
        allowed_values = ["UP", "DOWN"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this Host.

        Last update  # noqa: E501

        :return: The timestamp of this Host.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this Host.

        Last update  # noqa: E501

        :param timestamp: The timestamp of this Host.
        :type timestamp: str
        """

        self._timestamp = timestamp
