# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, short: str=None, host: str=None, state: str=None, timestamp: str=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param name: The name of this InlineResponse2002.  # noqa: E501
        :type name: str
        :param short: The short of this InlineResponse2002.  # noqa: E501
        :type short: str
        :param host: The host of this InlineResponse2002.  # noqa: E501
        :type host: str
        :param state: The state of this InlineResponse2002.  # noqa: E501
        :type state: str
        :param timestamp: The timestamp of this InlineResponse2002.  # noqa: E501
        :type timestamp: str
        """
        self.swagger_types = {
            'name': str,
            'short': str,
            'host': str,
            'state': str,
            'timestamp': str
        }

        self.attribute_map = {
            'name': 'name',
            'short': 'short',
            'host': 'host',
            'state': 'state',
            'timestamp': 'timestamp'
        }

        self._name = name
        self._short = short
        self._host = host
        self._state = state
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse2002.


        :return: The name of this InlineResponse2002.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse2002.


        :param name: The name of this InlineResponse2002.
        :type name: str
        """

        self._name = name

    @property
    def short(self) -> str:
        """Gets the short of this InlineResponse2002.


        :return: The short of this InlineResponse2002.
        :rtype: str
        """
        return self._short

    @short.setter
    def short(self, short: str):
        """Sets the short of this InlineResponse2002.


        :param short: The short of this InlineResponse2002.
        :type short: str
        """

        self._short = short

    @property
    def host(self) -> str:
        """Gets the host of this InlineResponse2002.


        :return: The host of this InlineResponse2002.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host: str):
        """Sets the host of this InlineResponse2002.


        :param host: The host of this InlineResponse2002.
        :type host: str
        """

        self._host = host

    @property
    def state(self) -> str:
        """Gets the state of this InlineResponse2002.


        :return: The state of this InlineResponse2002.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this InlineResponse2002.


        :param state: The state of this InlineResponse2002.
        :type state: str
        """

        self._state = state

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this InlineResponse2002.


        :return: The timestamp of this InlineResponse2002.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this InlineResponse2002.


        :param timestamp: The timestamp of this InlineResponse2002.
        :type timestamp: str
        """

        self._timestamp = timestamp
