# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, channels: List[Object]=None, state: str=None, timestamp: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param name: The name of this InlineResponse2001.  # noqa: E501
        :type name: str
        :param channels: The channels of this InlineResponse2001.  # noqa: E501
        :type channels: List[Object]
        :param state: The state of this InlineResponse2001.  # noqa: E501
        :type state: str
        :param timestamp: The timestamp of this InlineResponse2001.  # noqa: E501
        :type timestamp: str
        """
        self.swagger_types = {
            'name': str,
            'channels': List[Object],
            'state': str,
            'timestamp': str
        }

        self.attribute_map = {
            'name': 'name',
            'channels': 'channels',
            'state': 'state',
            'timestamp': 'timestamp'
        }
        self._name = name
        self._channels = channels
        self._state = state
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse2001.


        :return: The name of this InlineResponse2001.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse2001.


        :param name: The name of this InlineResponse2001.
        :type name: str
        """

        self._name = name

    @property
    def channels(self) -> List[Object]:
        """Gets the channels of this InlineResponse2001.


        :return: The channels of this InlineResponse2001.
        :rtype: List[Object]
        """
        return self._channels

    @channels.setter
    def channels(self, channels: List[Object]):
        """Sets the channels of this InlineResponse2001.


        :param channels: The channels of this InlineResponse2001.
        :type channels: List[Object]
        """

        self._channels = channels

    @property
    def state(self) -> str:
        """Gets the state of this InlineResponse2001.


        :return: The state of this InlineResponse2001.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this InlineResponse2001.


        :param state: The state of this InlineResponse2001.
        :type state: str
        """

        self._state = state

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this InlineResponse2001.


        :return: The timestamp of this InlineResponse2001.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this InlineResponse2001.


        :param timestamp: The timestamp of this InlineResponse2001.
        :type timestamp: str
        """

        self._timestamp = timestamp
