# coding: utf-8

"""
    PICKY: Python ICinga2 to KeYbase

    A Bridge between Icinga2's Notifications and Keybase  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Host(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'messages': 'dict(str, int)',
        'state': 'str',
        'timestamp': 'str'
    }

    attribute_map = {
        'name': 'name',
        'messages': 'messages',
        'state': 'state',
        'timestamp': 'timestamp'
    }

    def __init__(self, name=None, messages=None, state='UP', timestamp=None):  # noqa: E501
        """Host - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._messages = None
        self._state = None
        self._timestamp = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if messages is not None:
            self.messages = messages
        if state is not None:
            self.state = state
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def name(self):
        """Gets the name of this Host.  # noqa: E501

        Name of host to create  # noqa: E501

        :return: The name of this Host.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Host.

        Name of host to create  # noqa: E501

        :param name: The name of this Host.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def messages(self):
        """Gets the messages of this Host.  # noqa: E501


        :return: The messages of this Host.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this Host.


        :param messages: The messages of this Host.  # noqa: E501
        :type: dict(str, int)
        """

        self._messages = messages

    @property
    def state(self):
        """Gets the state of this Host.  # noqa: E501


        :return: The state of this Host.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Host.


        :param state: The state of this Host.  # noqa: E501
        :type: str
        """
        allowed_values = ["UP", "DOWN"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def timestamp(self):
        """Gets the timestamp of this Host.  # noqa: E501

        Last update  # noqa: E501

        :return: The timestamp of this Host.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Host.

        Last update  # noqa: E501

        :param timestamp: The timestamp of this Host.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Host, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Host):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
