# coding: utf-8

"""
    PICKY: Python ICinga2 to KeYbase

    A Bridge between Icinga2 Notifications and Keybase  # noqa: E501

    OpenAPI spec version: 1.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Service(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'state': 'str',
        'output': 'str',
        'timestamp': 'str',
        'updates': 'int',
        'sla': 'str',
        'note_type': 'str',
        'picky': 'str',
        'url': 'str'
    }

    attribute_map = {
        'name': 'name',
        'state': 'state',
        'output': 'output',
        'timestamp': 'timestamp',
        'updates': 'updates',
        'sla': 'sla',
        'note_type': 'note_type',
        'picky': 'picky',
        'url': 'url'
    }

    def __init__(self, name=None, state='OK', output='', timestamp=None, updates=0, sla='bronze', note_type='Problem', picky=None, url=None):  # noqa: E501
        """Service - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._state = None
        self._output = None
        self._timestamp = None
        self._updates = None
        self._sla = None
        self._note_type = None
        self._picky = None
        self._url = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if state is not None:
            self.state = state
        if output is not None:
            self.output = output
        if timestamp is not None:
            self.timestamp = timestamp
        if updates is not None:
            self.updates = updates
        if sla is not None:
            self.sla = sla
        if note_type is not None:
            self.note_type = note_type
        if picky is not None:
            self.picky = picky
        if url is not None:
            self.url = url

    @property
    def name(self):
        """Gets the name of this Service.  # noqa: E501

        Short name of the service  # noqa: E501

        :return: The name of this Service.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Service.

        Short name of the service  # noqa: E501

        :param name: The name of this Service.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def state(self):
        """Gets the state of this Service.  # noqa: E501


        :return: The state of this Service.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Service.


        :param state: The state of this Service.  # noqa: E501
        :type: str
        """
        allowed_values = ["OK", "WARNING", "CRITICAL", "UNKNOWN"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def output(self):
        """Gets the output of this Service.  # noqa: E501

        Output of service check command  # noqa: E501

        :return: The output of this Service.  # noqa: E501
        :rtype: str
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this Service.

        Output of service check command  # noqa: E501

        :param output: The output of this Service.  # noqa: E501
        :type: str
        """

        self._output = output

    @property
    def timestamp(self):
        """Gets the timestamp of this Service.  # noqa: E501

        Last update  # noqa: E501

        :return: The timestamp of this Service.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Service.

        Last update  # noqa: E501

        :param timestamp: The timestamp of this Service.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    @property
    def updates(self):
        """Gets the updates of this Service.  # noqa: E501

        Update counter  # noqa: E501

        :return: The updates of this Service.  # noqa: E501
        :rtype: int
        """
        return self._updates

    @updates.setter
    def updates(self, updates):
        """Sets the updates of this Service.

        Update counter  # noqa: E501

        :param updates: The updates of this Service.  # noqa: E501
        :type: int
        """

        self._updates = updates

    @property
    def sla(self):
        """Gets the sla of this Service.  # noqa: E501


        :return: The sla of this Service.  # noqa: E501
        :rtype: str
        """
        return self._sla

    @sla.setter
    def sla(self, sla):
        """Sets the sla of this Service.


        :param sla: The sla of this Service.  # noqa: E501
        :type: str
        """
        allowed_values = ["gold", "silver", "bronze"]  # noqa: E501
        if sla not in allowed_values:
            raise ValueError(
                "Invalid value for `sla` ({0}), must be one of {1}"  # noqa: E501
                .format(sla, allowed_values)
            )

        self._sla = sla

    @property
    def note_type(self):
        """Gets the note_type of this Service.  # noqa: E501


        :return: The note_type of this Service.  # noqa: E501
        :rtype: str
        """
        return self._note_type

    @note_type.setter
    def note_type(self, note_type):
        """Sets the note_type of this Service.


        :param note_type: The note_type of this Service.  # noqa: E501
        :type: str
        """
        allowed_values = ["Problem", "Acknowledgement", "Recovery"]  # noqa: E501
        if note_type not in allowed_values:
            raise ValueError(
                "Invalid value for `note_type` ({0}), must be one of {1}"  # noqa: E501
                .format(note_type, allowed_values)
            )

        self._note_type = note_type

    @property
    def picky(self):
        """Gets the picky of this Service.  # noqa: E501

        Stub neatly formatted for Keybase  # noqa: E501

        :return: The picky of this Service.  # noqa: E501
        :rtype: str
        """
        return self._picky

    @picky.setter
    def picky(self, picky):
        """Sets the picky of this Service.

        Stub neatly formatted for Keybase  # noqa: E501

        :param picky: The picky of this Service.  # noqa: E501
        :type: str
        """

        self._picky = picky

    @property
    def url(self):
        """Gets the url of this Service.  # noqa: E501

        Link to this object  # noqa: E501

        :return: The url of this Service.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Service.

        Link to this object  # noqa: E501

        :param url: The url of this Service.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Service, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Service):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
