# coding: utf-8

"""
    PICKY: Python ICinga2 to KeYbase

    A Bridge between Icinga2 Notifications and Keybase  # noqa: E501

    OpenAPI spec version: 1.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.services_api import ServicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self):
        self.api = api.services_api.ServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_services(self):
        """Test case for get_services

        Get all services of a host  # noqa: E501
        """
        pass

    def test_put_service(self):
        """Test case for put_service

        Service notification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
