# coding: utf-8

"""
    PICKY: Python ICinga2 to KeYbase

    A Bridge between Icinga2's Notifications and Keybase  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.services_api import ServicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self):
        self.api = api.services_api.ServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_services_create(self):
        """Test case for services_create

        Create a service and add it to the services list  # noqa: E501
        """
        pass

    def test_services_delete(self):
        """Test case for services_delete

        Delete a service from the services list  # noqa: E501
        """
        pass

    def test_services_read_all(self):
        """Test case for services_read_all

        Read the entire services list  # noqa: E501
        """
        pass

    def test_services_read_one(self):
        """Test case for services_read_one

        Read one service from the services list  # noqa: E501
        """
        pass

    def test_services_update(self):
        """Test case for services_update

        Update a service in the services list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
