# coding: utf-8

"""
    PICKY: Python ICinga2 to KeYbase

    A Bridge between Icinga2 Notifications and Keybase  # noqa: E501

    OpenAPI spec version: 1.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.hosts_api import HostsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHostsApi(unittest.TestCase):
    """HostsApi unit test stubs"""

    def setUp(self):
        self.api = api.hosts_api.HostsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_hosts(self):
        """Test case for get_hosts

        Get all hosts in a channel  # noqa: E501
        """
        pass

    def test_put_host(self):
        """Test case for put_host

        Host notification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
