# coding: utf-8

"""
    PICKY: Python ICinga2 to KeYbase

    A Bridge between Icinga2's Notifications and Keybase  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.host import Host  # noqa: E501
from swagger_client.rest import ApiException


class TestHost(unittest.TestCase):
    """Host unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHost(self):
        """Test Host"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.host.Host()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
