# coding: utf-8

"""
    PICKY: Python ICinga2 to KeYbase

    A Bridge between Icinga2 Notifications and Keybase  # noqa: E501

    OpenAPI spec version: 1.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.channel import Channel  # noqa: E501
from swagger_client.rest import ApiException


class TestChannel(unittest.TestCase):
    """Channel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannel(self):
        """Test Channel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.channel.Channel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
